TRAIN_DATA = [('do you want to eat hot dog hamburger or french fries', {'entities': [(19, 26, 'MISC'), (27, 36, 'MISC'), (40, 52, 'MISC')]}),
('are you tired or sad', {'entities': [(8, 13, 'MISC'), (17, 20, 'MISC')]}),
('are you hungry or thirsty', {'entities': [(8, 14, 'MISC'), (18, 25, 'MISC')]}),
('do you want one two or three spoons', {'entities': [(12, 15, 'MISC'), (16, 19, 'MISC'), (23, 28, 'MISC')]}),
('do you want to water juice soda or lemonade', {'entities': [(15, 20, 'MISC'), (21, 26, 'MISC'), (27, 31, 'MISC'), (35, 43, 'MISC')]}),
('is it a photopic or scotopic response', {'entities': [(8, 16, 'MISC'), (20, 28, 'MISC')]}),
('is the index 1 or 1.33', {'entities': [(13, 14, 'MISC'), (18, 22, 'MISC')]}),
('how old are you 7 or 8', {'entities': [(16, 17, 'MISC'), (21, 22, 'MISC')]}),
('do you like fruits that are sweet or sour', {'entities': [(37, 41, 'MISC'), (28, 33, 'MISC')]}),
('do you want a sour or sweet fruit', {'entities': [(22, 27, 'MISC'), (14, 18, 'MISC')]}),
('do you prefer android or ios', {'entities': [(14, 21, 'MISC'), (25, 28, 'MISC')]}),
('which item would you like a b or c', {'entities': [(26, 27, 'MISC'), (28, 29, 'MISC'), (3, 4, 'MISC')]}),
('which is the correct answer a b or c', {'entities': [(21, 22, 'MISC'), (30, 31, 'MISC'), (3, 4, 'MISC')]}),
('which item would you like a soda tea or coffee', {'entities': [(28, 32, 'MISC'), (33, 36, 'MISC'), (40, 46, 'MISC')]}),
('do you want to fries hamburguer beans or rice', {'entities': [(15, 20, 'MISC'), (21, 31, 'MISC'), (32, 37, 'MISC'), (41, 45, 'MISC')]}),
('do you want to sleep walk eat or dream', {'entities': [(15, 20, 'MISC'), (21, 25, 'MISC'), (26, 29, 'MISC'), (33, 38, 'MISC')]}),
('do you want to sleep with or without a pillow', {'entities': [(21, 25, 'MISC'), (29, 36, 'MISC')]}),
('do you want banana with or without apple', {'entities': [(19, 23, 'MISC'), (27, 34, 'MISC')]}),
('you want want banana apple or salad', {'entities': [(14, 20, 'MISC'), (21, 26, 'MISC'), (30, 35, 'MISC')]}),
('do you want apple with or without salad', {'entities': [(18, 22, 'MISC'), (26, 33, 'MISC')]}),
('you want like apple salad or fruit', {'entities': [(14, 19, 'MISC'), (20, 25, 'MISC'), (29, 34, 'MISC')]}),
('do you want salad with or without fruit', {'entities': [(18, 22, 'MISC'), (26, 33, 'MISC')]}),
('you want wish salad fruit or vanilla', {'entities': [(14, 19, 'MISC'), (20, 25, 'MISC'), (29, 36, 'MISC')]}),
('do you want fruit with or without vanilla', {'entities': [(18, 22, 'MISC'), (26, 33, 'MISC')]}),
('you want apreciate fruit vanilla or pizza', {'entities': [(19, 24, 'MISC'), (25, 32, 'MISC'), (36, 41, 'MISC')]}),
('do you want vanilla with or without pizza', {'entities': [(20, 24, 'MISC'), (28, 35, 'MISC')]}),
('you want pretend vanilla pizza or hamburguer', {'entities': [(17, 24, 'MISC'), (25, 30, 'MISC'), (34, 44, 'MISC')]}),
('do you want pizza with or without hamburguer', {'entities': [(18, 22, 'MISC'), (26, 33, 'MISC')]}),
('you want plan pizza hamburguer or chocolate', {'entities': [(14, 19, 'MISC'), (20, 30, 'MISC'), (34, 43, 'MISC')]}),
('do you want hamburguer with or without chocolate', {'entities': [(23, 27, 'MISC'), (31, 38, 'MISC')]}),
('you want need hamburguer chocolate or rice', {'entities': [(14, 24, 'MISC'), (25, 34, 'MISC'), (38, 42, 'MISC')]}),
('do you want chocolate with or without rice', {'entities': [(22, 26, 'MISC'), (30, 37, 'MISC')]}),
('you want choose chocolate rice or a', {'entities': [(16, 25, 'MISC'), (26, 30, 'MISC'), (5, 6, 'MISC')]}),
('do you want rice with or without a', {'entities': [(17, 21, 'MISC'), (25, 32, 'MISC')]}),
('you want love rice a or b', {'entities': [(14, 18, 'MISC'), (5, 6, 'MISC'), (24, 25, 'MISC')]}),
('do you want a with or without b', {'entities': [(14, 18, 'MISC'), (22, 29, 'MISC')]}),
('you want eat a b or c', {'entities': [(5, 6, 'MISC'), (15, 16, 'MISC'), (20, 21, 'MISC')]}),
('do you want b with or without c', {'entities': [(14, 18, 'MISC'), (22, 29, 'MISC')]}),
('do you want to go to the a or to the b', {'entities': [(8, 9, 'MISC'), (37, 38, 'MISC')]}),
('do you want to go to the b or to the c', {'entities': [(25, 26, 'MISC'), (37, 38, 'MISC')]}),
('do you want to go to the c or to the grandmother', {'entities': [(25, 26, 'MISC'), (37, 48, 'MISC')]}),
('do you want to go to the grandmother or to the school', {'entities': [(25, 36, 'MISC'), (47, 53, 'MISC')]}),
('do you want to go to the school or to the therapy', {'entities': [(25, 31, 'MISC'), (42, 49, 'MISC')]}),
('do you want to go to the therapy or to the park', {'entities': [(25, 32, 'MISC'), (43, 47, 'MISC')]}),
('do you want to go to the park or to the shopping', {'entities': [(25, 29, 'MISC'), (40, 48, 'MISC')]}),
('do you want to go to the shopping or to the club', {'entities': [(25, 33, 'MISC'), (44, 48, 'MISC')]}),
('do you want to go to the club or to the chess', {'entities': [(25, 29, 'MISC'), (40, 45, 'MISC')]}),
('do you want a or b', {'entities': [(8, 9, 'MISC'), (17, 18, 'MISC')]}),
('the result is a b or c', {'entities': [(14, 15, 'MISC'), (16, 17, 'MISC'), (21, 22, 'MISC')]}),
('do you want b or c', {'entities': [(12, 13, 'MISC'), (17, 18, 'MISC')]}),
('the result is b c or play', {'entities': [(14, 15, 'MISC'), (16, 17, 'MISC'), (21, 25, 'MISC')]}),
('do you want c or play', {'entities': [(12, 13, 'MISC'), (17, 21, 'MISC')]}),
('the result is c play or run', {'entities': [(14, 15, 'MISC'), (16, 20, 'MISC'), (24, 27, 'MISC')]}),
('do you want play or run', {'entities': [(12, 16, 'MISC'), (20, 23, 'MISC')]}),
('the result is play run or lift', {'entities': [(14, 18, 'MISC'), (19, 22, 'MISC'), (26, 30, 'MISC')]}),
('do you want run or lift', {'entities': [(12, 15, 'MISC'), (19, 23, 'MISC')]}),
('the result is run lift or jump', {'entities': [(14, 17, 'MISC'), (18, 22, 'MISC'), (26, 30, 'MISC')]}),
('do you want lift or jump', {'entities': [(12, 16, 'MISC'), (20, 24, 'MISC')]}),
('the result is lift jump or sleep', {'entities': [(14, 18, 'MISC'), (19, 23, 'MISC'), (27, 32, 'MISC')]}),
('do you want jump or sleep', {'entities': [(12, 16, 'MISC'), (20, 25, 'MISC')]}),
('the result is jump sleep or dream', {'entities': [(14, 18, 'MISC'), (19, 24, 'MISC'), (28, 33, 'MISC')]}),
('do you want sleep or dream', {'entities': [(12, 17, 'MISC'), (21, 26, 'MISC')]}),
('the result is sleep dream or fly', {'entities': [(14, 19, 'MISC'), (20, 25, 'MISC'), (29, 32, 'MISC')]}),
('do you want dream or fly', {'entities': [(12, 17, 'MISC'), (21, 24, 'MISC')]}),
('the result is dream fly or work', {'entities': [(14, 19, 'MISC'), (20, 23, 'MISC'), (27, 31, 'MISC')]}),
('do you want fly or work', {'entities': [(12, 15, 'MISC'), (19, 23, 'MISC')]}),
('the result is fly work or live', {'entities': [(14, 17, 'MISC'), (18, 22, 'MISC'), (26, 30, 'MISC')]}),
('do you want work or live', {'entities': [(12, 16, 'MISC'), (20, 24, 'MISC')]}),
]