TRAIN_DATA = [('voce quer comer batata frita cachorro quente ou hamburguer', {'entities': [(16, 28, 'MISC'), (29, 44, 'MISC'), (48, 58, 'MISC')]}),
('voce está triste ou cansado', {'entities': [(10, 16, 'MISC'), (20, 27, 'MISC')]}),
('você está com fome ou com sede', {'entities': [(14, 18, 'MISC'), (26, 30, 'MISC')]}),
('voce quer uma duas ou tres colheres', {'entities': [(14, 18, 'MISC'), (22, 26, 'MISC')]}),
('você quer água suco refrigerante ou limonada', {'entities': [(10, 14, 'MISC'), (15, 19, 'MISC'), (20, 32, 'MISC'), (36, 44, 'MISC')]}),
('é uma resposta fotópica ou escotópica', {'entities': [(15, 23, 'MISC'), (27, 37, 'MISC')]}),
('o índice é 1 ou 1.33', {'entities': [(11, 12, 'MISC'), (16, 20, 'MISC')]}),
('quantos anos você tem 7 ou 8', {'entities': [(22, 23, 'MISC'), (27, 28, 'MISC')]}),
('você gosta de frutas doces ou azedas', {'entities': [(21, 26, 'MISC'), (30, 36, 'MISC')]}),
('você quer uma fruta azeda ou doce', {'entities': [(20, 25, 'MISC'), (29, 33, 'MISC')]}),
('você prefere android ou ios', {'entities': [(13, 20, 'MISC'), (24, 27, 'MISC')]}),
('qual item você gostaria a b ou c', {'entities': [(2, 3, 'MISC'), (26, 27, 'MISC'), (12, 13, 'MISC')]}),
('qual é a resposta correta a b ou c', {'entities': [(2, 3, 'MISC'), (28, 29, 'MISC'), (18, 19, 'MISC')]}),
('qual item você gostaria um chá um café ou um refrigerante', {'entities': [(27, 30, 'MISC'), (34, 38, 'MISC'), (45, 57, 'MISC')]}),
('voce quer fritas hambúrguer feijao ou arroz', {'entities': [(10, 16, 'MISC'), (17, 27, 'MISC'), (28, 34, 'MISC'), (38, 43, 'MISC')]}),
('voce quer dormir andar comer ou sonhar', {'entities': [(10, 16, 'MISC'), (17, 22, 'MISC'), (23, 28, 'MISC'), (32, 38, 'MISC')]}),
('voce quer dormir com ou sem travesseiro', {'entities': [(17, 20, 'MISC'), (24, 27, 'MISC')]}),
('voce quer ir na casa da sua tia ou ficar em casa', {'entities': [(28, 31, 'MISC'), (16, 20, 'MISC')]}),
]