TRAIN_DATA = [('voce quer comer batata frita cachorro quente ou hamburguer', {'entities': [(16, 28, 'MISC'), (29, 44, 'MISC'), (48, 58, 'MISC')]}),
('voce está triste ou cansado', {'entities': [(10, 16, 'MISC'), (20, 27, 'MISC')]}),
('você está com fome ou com sede', {'entities': [(14, 18, 'MISC'), (26, 30, 'MISC')]}),
('voce quer uma duas ou tres colheres', {'entities': [(14, 18, 'MISC'), (22, 26, 'MISC')]}),
('você quer água suco refrigerante ou limonada', {'entities': [(10, 14, 'MISC'), (15, 19, 'MISC'), (20, 32, 'MISC'), (36, 44, 'MISC')]}),
('é uma resposta fotópica ou escotópica', {'entities': [(15, 23, 'MISC'), (27, 37, 'MISC')]}),
('o índice é 1 ou 1.33', {'entities': [(11, 12, 'MISC'), (16, 20, 'MISC')]}),
('quantos anos você tem 7 ou 8', {'entities': [(22, 23, 'MISC'), (27, 28, 'MISC')]}),
('você gosta de frutas doces ou azedas', {'entities': [(21, 26, 'MISC'), (30, 36, 'MISC')]}),
('você quer uma fruta azeda ou doce', {'entities': [(20, 25, 'MISC'), (29, 33, 'MISC')]}),
('você prefere android ou ios', {'entities': [(13, 20, 'MISC'), (24, 27, 'MISC')]}),
('qual item você gostaria a b ou c', {'entities': [(2, 3, 'MISC'), (26, 27, 'MISC'), (12, 13, 'MISC')]}),
('qual é a resposta correta a b ou c', {'entities': [(2, 3, 'MISC'), (28, 29, 'MISC'), (18, 19, 'MISC')]}),
('qual item você gostaria um chá um café ou um refrigerante', {'entities': [(27, 30, 'MISC'), (34, 38, 'MISC'), (45, 57, 'MISC')]}),
('voce quer fritas hambúrguer feijao ou arroz', {'entities': [(10, 16, 'MISC'), (17, 27, 'MISC'), (28, 34, 'MISC'), (38, 43, 'MISC')]}),
('voce quer dormir andar comer ou sonhar', {'entities': [(10, 16, 'MISC'), (17, 22, 'MISC'), (23, 28, 'MISC'), (32, 38, 'MISC')]}),
('voce quer dormir com ou sem travesseiro', {'entities': [(17, 20, 'MISC'), (24, 27, 'MISC')]}),
('voce quer ir banana ou ao maça', {'entities': [(13, 19, 'MISC'), (26, 30, 'MISC')]}),
('voce quer ir maça ou ao salada', {'entities': [(13, 17, 'MISC'), (24, 30, 'MISC')]}),
('voce quer ir salada ou ao fruta', {'entities': [(13, 19, 'MISC'), (26, 31, 'MISC')]}),
('voce quer ir fruta ou ao baunilha', {'entities': [(13, 18, 'MISC'), (25, 33, 'MISC')]}),
('voce quer ir baunilha ou ao pizza', {'entities': [(13, 21, 'MISC'), (28, 33, 'MISC')]}),
('voce quer ir pizza ou ao hamburguer', {'entities': [(13, 18, 'MISC'), (25, 35, 'MISC')]}),
('voce quer ir hamburguer ou ao prestigio', {'entities': [(13, 23, 'MISC'), (30, 39, 'MISC')]}),
('voce quer ir prestigio ou ao chocolate', {'entities': [(13, 22, 'MISC'), (29, 38, 'MISC')]}),
('voce quer ir chocolate ou ao rapadura', {'entities': [(13, 22, 'MISC'), (29, 37, 'MISC')]}),
('voce quer ir rapadura ou ao arroz', {'entities': [(13, 21, 'MISC'), (28, 33, 'MISC')]}),
('voce quer ir casa da vo ou ao escola', {'entities': [(13, 23, 'MISC'), (30, 36, 'MISC')]}),
('voce quer ir escola ou ao cyber', {'entities': [(13, 19, 'MISC'), (26, 31, 'MISC')]}),
('voce quer ir cyber ou ao terapia', {'entities': [(13, 18, 'MISC'), (25, 32, 'MISC')]}),
('voce quer ir terapia ou ao parque', {'entities': [(13, 20, 'MISC'), (27, 33, 'MISC')]}),
('voce quer ir parque ou ao shopping', {'entities': [(13, 19, 'MISC'), (26, 34, 'MISC')]}),
('voce quer ir brincar ou ao correr', {'entities': [(13, 20, 'MISC'), (27, 33, 'MISC')]}),
('voce quer ir correr ou ao levantar', {'entities': [(13, 19, 'MISC'), (26, 34, 'MISC')]}),
('voce quer ir levantar ou ao pular', {'entities': [(13, 21, 'MISC'), (28, 33, 'MISC')]}),
('voce quer ir pular ou ao jogar', {'entities': [(13, 18, 'MISC'), (25, 30, 'MISC')]}),
('voce quer ir jogar ou ao deitar', {'entities': [(13, 18, 'MISC'), (25, 31, 'MISC')]}),
('voce quer ir deitar ou ao dormir', {'entities': [(13, 19, 'MISC'), (26, 32, 'MISC')]}),
]