TRAIN_DATA = [('voce quer ir banana ou ao maça', {'entities': [(13, 19, 'MISC'), (26, 30, 'MISC')]}),
('voce quer ir maça ou ao salada', {'entities': [(13, 17, 'MISC'), (24, 30, 'MISC')]}),
('voce quer ir salada ou ao fruta', {'entities': [(13, 19, 'MISC'), (26, 31, 'MISC')]}),
('voce quer ir fruta ou ao baunilha', {'entities': [(13, 18, 'MISC'), (25, 33, 'MISC')]}),
('voce quer ir baunilha ou ao pizza', {'entities': [(13, 21, 'MISC'), (28, 33, 'MISC')]}),
('voce quer ir pizza ou ao hamburguer', {'entities': [(13, 18, 'MISC'), (25, 35, 'MISC')]}),
('voce quer ir hamburguer ou ao prestigio', {'entities': [(13, 23, 'MISC'), (30, 39, 'MISC')]}),
('voce quer ir prestigio ou ao chocolate', {'entities': [(13, 22, 'MISC'), (29, 38, 'MISC')]}),
('voce quer ir chocolate ou ao rapadura', {'entities': [(13, 22, 'MISC'), (29, 37, 'MISC')]}),
('voce quer ir rapadura ou ao arroz', {'entities': [(13, 21, 'MISC'), (28, 33, 'MISC')]}),
('voce quer ir casa da vo ou ao escola', {'entities': [(13, 23, 'MISC'), (30, 36, 'MISC')]}),
('voce quer ir escola ou ao cyber', {'entities': [(13, 19, 'MISC'), (26, 31, 'MISC')]}),
('voce quer ir cyber ou ao terapia', {'entities': [(13, 18, 'MISC'), (25, 32, 'MISC')]}),
('voce quer ir terapia ou ao parque', {'entities': [(13, 20, 'MISC'), (27, 33, 'MISC')]}),
('voce quer ir parque ou ao shopping', {'entities': [(13, 19, 'MISC'), (26, 34, 'MISC')]}),
('voce quer ir brincar ou ao correr', {'entities': [(13, 20, 'MISC'), (27, 33, 'MISC')]}),
('voce quer ir correr ou ao levantar', {'entities': [(13, 19, 'MISC'), (26, 34, 'MISC')]}),
('voce quer ir levantar ou ao pular', {'entities': [(13, 21, 'MISC'), (28, 33, 'MISC')]}),
('voce quer ir pular ou ao jogar', {'entities': [(13, 18, 'MISC'), (25, 30, 'MISC')]}),
('voce quer ir jogar ou ao deitar', {'entities': [(13, 18, 'MISC'), (25, 31, 'MISC')]}),
('voce quer ir deitar ou ao dormir', {'entities': [(13, 19, 'MISC'), (26, 32, 'MISC')]}),
]